#!/bin/bash

echo 'Waiting 10 seconds for things to start up and settle down...'
sleep 10


# Every day do a backup.
day_in_seconds=86400;
while true; do
  echo "Running backup"
  duply site_data backup
  echo "Waiting '$day_in_seconds' seconds for next backup"
  sleep "$day_in_seconds"
done
